const completedJobsList = [
	{
		jobID: 2,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 4,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 5,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 15,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 16,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 17,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 18,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 19,
		title: "Marathon",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 20,
		title: "TestProject",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 24,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 25,
		title: "manu",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 26,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 27,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 28,
		title: "123",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 29,
		title: "1234",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 30,
		title: "Sample",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 31,
		title: "1",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 32,
		title: "1",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 33,
		title: "2",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 34,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 35,
		title: "TestProject2",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 36,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 37,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 38,
		title: "AWS ",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 39,
		title: "AWS TEST",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 40,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 41,
		title: "hahj",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 42,
		title: "hahj",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 44,
		title: "nnaj",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 46,
		title: "Best Western",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 50,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 51,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 52,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 53,
		title: "sample",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 54,
		title: "ABC",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 56,
		title: "sample project",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 57,
		title: "XYZProject",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 58,
		title: "test",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 59,
		title: "b",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 60,
		title: "test",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 61,
		title: "SAMPLE",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 62,
		title: "SAMPLE",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 63,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 64,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 65,
		title: "TestRandom",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 66,
		title: "RandomProjectName",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 67,
		title: "test",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 68,
		title: "Best Western International",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 69,
		title: "a",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 70,
		title: "RandomProjectName",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 71,
		title: "SecretProject",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 77,
		title: "score",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 79,
		title: "RandomProjectName2",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 80,
		title: "RandomProjectName2",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 82,
		title: "YetAnotherRandomProject",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 84,
		title: "Test Project 2",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 96,
		title: "CannotStopWithRandomProjects",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 111,
		title: "S.H.I.E.L.D",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 113,
		title: "Avengers",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 114,
		title: "Justice League",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 124,
		title: "TestProject",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 126,
		title: "Justice League",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 127,
		title: "Test Project",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
	{
		jobID: 133,
		title: "test project",
		completionDate: "July 1, 2021",
		rating: 5.0,
		comment: "Nice and Good to work with.",
		fee: 50,
		feeType: "Fixed",
	},
];

export default completedJobsList;
